#pragma config(Motor,  port2,           LClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LUDriving,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LDDriving,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RUDriving,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RDDriving,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1)
  {
  	//Driving
		motor[LUDriving] = vexRT[Ch3];
		motor[LDDriving] = vexRT[Ch3];
		motor[RUDriving] = vexRT[Ch2];
		motor[RDDriving] = vexRT[Ch2];
		//Arm
		if (vexRT[Btn5U] == 1)
			{
				motor[LArm] = 127;
				motor[RArm] = 127;
			}
		else if (vexRT[Btn5D] == 1)
			{
				motor[LArm] = -127;
				motor[RArm] = -127;
			}
		else
			{
				motor[LArm] = 0;
				motor[RArm] = 0;
			}
			//Claw
		if (vexRT[Btn6D] == 1)
			{
				motor[LClaw] = -127;
				motor[RClaw] = -127;
			}
		else if (vexRT[Btn6U] == 1)
			{
				motor[LClaw] = 127;
				motor[RClaw] = 127;
			}
		else
			{
				motor[LClaw] = 0;
				motor[RClaw] = 0;
			}
	}
}
