#pragma config(Motor,  port5,           LClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Storage,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		motor[LDrive] = vexRT[Ch3];
		motor[RDrive] = vexRT[Ch2];
		motor[LClaw] = vexRT[Btn6UXmtr2];
		motor[RClaw] = vexRT[Btn5UXmtr2];
		motor[Storage] = vexRT[Btn8DXmtr2];
	}
}
