#pragma config(Motor,  port5,           LClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	//move forward
	motor[LDrive] = 127;
	motor[RDrive] = 127;
	wait1Msec(4000);
	//move backward
	motor[LDrive] = -127;
	motor[RDrive] = -127;
	motor[LClaw] = -127;
	motor[RClaw] = -127;
	wait1Msec(3000);
	//wait
	motor[LDrive] = 0;
	motor[RDrive] = 0;
	wait1Msec(7000);
}

task usercontrol()
{
	while(1==1)
	{
		//Driving
		motor[LDrive] = vexRT[Ch3];
		motor[RDrive] = vexRT[Ch2];
		//Left Claw
		if(vexRT[Btn6U] == 1)
		{
			motor[LClaw] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[LClaw] = -127;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[LClaw] = 127;
		}
		else
		{
			motor[LClaw] = 0;
		}
		//Right Claw
		if(vexRT[Btn5U] == 1)
		{
			motor[RClaw] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[RClaw] = -127;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[RClaw] = 127;
		}
		else
		{
			motor[RClaw] = 0;
		}
	}
}
