#pragma config(Motor,  port2,           LClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LArm,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LUDriving,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LDDriving,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RUDriving,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RDDriving,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void endDrive()
{
	motor[LUDriving] = 0;
	motor[LDDriving] = 0;
	motor[RUDriving] = 0;
	motor[RDDriving] = 0;
}
void moveForward(float time)
{
	motor[LUDriving] = 127;
	motor[LDDriving] = 127;
	motor[RUDriving] = 127;
	motor[RDDriving] = 127;
	delay(time);
	endDrive();
}
void moveBackward(float time)
{
	motor[LUDriving] = -127;
	motor[LDDriving] = -127;
	motor[RUDriving] = -127;
	motor[RDDriving] = -127;
	delay(time);
	endDrive();
}
void turnLeft(float time)
{
	motor[LUDriving] = -40;
	motor[LDDriving] = -40;
	motor[RUDriving] = 40;
	motor[RDDriving] = 40;
	delay(time);
	endDrive();
}
void turnRight(float time)
{
	motor[LUDriving] = 40;
	motor[LDDriving] = 40;
	motor[RUDriving] = -40;
	motor[RDDriving] = -40;
	delay(time);
	endDrive();
}
task main()
{
	moveForward(1200);
	moveBackward(1200);
	turnRight(1000);
	moveForward(2500);
	//pick up cube
	motor[LClaw] = -127;
	motor[RClaw] = -127;
	delay(500);
	motor[LClaw] = 0;
	motor[RClaw] = 0;
	moveBackward(500);
	//lift cube
	motor[LArm] = 19;
	motor[RArm] = 19;
	delay(500);
	motor[LArm] = 19;
	motor[RArm] = 19;
	//drop cube
	motor[LClaw] = 127;
	motor[RClaw] = 127;
	delay(500);
	motor[LClaw] = 0;
	motor[RClaw] = 0;
}
